# Generated by Django 3.0.3 on 2020-03-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0002_auto_20200301_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ci',
        ),
        migrations.AddField(
            model_name='incidente',
            name='document',
            field=models.CharField(default='00000', max_length=50, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='document',
            field=models.CharField(default='0000', max_length=10, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=0, max_length=50, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidente',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='hour',
            field=models.CharField(max_length=4, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='zone',
            field=models.CharField(max_length=20, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year'),
        ),
    ]
