# Generated by Django 3.0.3 on 2020-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0003_auto_20200301_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='document',
            field=models.CharField(max_length=50, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='document',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Documento'),
        ),
    ]
